[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.0.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
async-trait = "0.1.81"

[dependencies.tokio]
version = "1.38.0"
features = ["full"]