[package]
name = "kvdb-lib"
version = "0.1.0"
authors = ["messenger_qs 139318962+messengernew@users.noreply.github.com"]
edition = "2021"
description = "A simple thread-safe key-value storage library using DashMap."
license = "MIT"
repository = "https://github.com/messenger_qs/kvdb-lib"
readme = "README.md"
homepage = "https://github.com/messenger_qs/kvdb-lib"
documentation = "https://docs.rs/kvdb-lib"

[dependencies]
dashmap = "6.0.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3